name: Feature request
description: Request a new feature
labels: ["T-feature"]
body:
    - type: markdown
      attributes:
          value: |
              Please ensure that this feature has not already been requested in the issue tracker.

              Thanks for taking the time to help improve Heimdall!
    - type: dropdown
      attributes:
          label: Component
          description: What component is the feature request for?
          multiple: true
          options:
              - Bifrost
              - Heimdall (Core)
              - Heimdall (CLI)
              - Other (please specify)
      validations:
          required: true
    - type: textarea
      attributes:
          label: Describe the feature you would like
          description: Please also describe what the feature is aiming to solve, if relevant.
      validations:
          required: true
