name: Improvement
description: Request an improvement to an existing feature
title: "[Improvement]: "
labels: ["T: Improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure this has not already been addressed in the issue tracker.

        Thank you!
  - type: checkboxes
    attributes:
      label: Please check the following
      options:
        - label: This is not a duplicate request
        - label: I have checked that this is not in development
  - type: textarea
    attributes:
      label: Type a detailed explanation of your improvement request here.
    validations:
      required: true
