name: Benchmarks (On Push)

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run benchmarks
        id: benchmark
        run: |
          RESULT=$(sh scripts/benchmark | awk '/Benchmark results:/,0')
          echo "result=$RESULT >> $GITHUB_OUTPUT"

      - name: Create PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            "<details><summary>Benchmark results</summary>\n\n\`\`\`\n${{ steps.benchmark.outputs.result }}\n\`\`\`</details>"
          comment_tag: benchmarks
